// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RequestsManagementSystem.Data;

#nullable disable

namespace RequestsManagementSystem.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250201152952_map-entities")]
    partial class mapentities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RequestsManagementSystem.Core.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("AdditonalCasualLeaveCount")
                        .HasColumnType("int");

                    b.Property<double>("AdditonalRegularLeaveCount")
                        .HasColumnType("float");

                    b.Property<DateOnly>("DateOfEmployment")
                        .HasColumnType("date");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EmployeeLevelId")
                        .HasColumnType("int");

                    b.Property<short>("EmployeeRole")
                        .HasColumnType("smallint");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("EmployeeLevelId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("RequestsManagementSystem.Core.Entities.EmployeeLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("CasualLeavePerMonth")
                        .HasColumnType("real");

                    b.Property<int>("CasualLeavePerYear")
                        .HasColumnType("int");

                    b.Property<string>("LevelDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<float>("RegularLeaveperMonth")
                        .HasColumnType("real");

                    b.Property<int>("RegularLeaveperYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EmployeeLevel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CasualLeavePerMonth = 0f,
                            CasualLeavePerYear = 6,
                            LevelDescription = "الفأة أ",
                            LevelName = "A",
                            OrderId = 1,
                            RegularLeaveperMonth = 1f,
                            RegularLeaveperYear = 15
                        },
                        new
                        {
                            Id = 2,
                            CasualLeavePerMonth = 0f,
                            CasualLeavePerYear = 6,
                            LevelDescription = "الفأة ب",
                            LevelName = "B",
                            OrderId = 2,
                            RegularLeaveperMonth = 2f,
                            RegularLeaveperYear = 24
                        });
                });

            modelBuilder.Entity("RequestsManagementSystem.Core.Entities.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Itinerary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RespondDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RespondMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("SeenStatus")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<int>("SubstituteEmployeeId")
                        .HasColumnType("int");

                    b.Property<short>("Title")
                        .HasColumnType("smallint");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("TransactionId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SubstituteEmployeeId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("RequestsManagementSystem.Core.Entities.Employee", b =>
                {
                    b.HasOne("RequestsManagementSystem.Core.Entities.EmployeeLevel", "EmployeeLevel")
                        .WithMany()
                        .HasForeignKey("EmployeeLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RequestsManagementSystem.Core.Entities.Employee", "Manager")
                        .WithMany("ManagerStaff")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EmployeeLevel");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("RequestsManagementSystem.Core.Entities.Transaction", b =>
                {
                    b.HasOne("RequestsManagementSystem.Core.Entities.Employee", "Employee")
                        .WithMany("Transactions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RequestsManagementSystem.Core.Entities.Employee", "SubstituteEmployee")
                        .WithMany()
                        .HasForeignKey("SubstituteEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("SubstituteEmployee");
                });

            modelBuilder.Entity("RequestsManagementSystem.Core.Entities.Employee", b =>
                {
                    b.Navigation("ManagerStaff");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
