// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RequestsManagementSystem.Data;

#nullable disable

namespace RequestsManagementSystem.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250329090920_parentType")]
    partial class parentType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RequestsManagementSystem.Core.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("DateOfEmployment")
                        .HasColumnType("date");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EmployeeLevelId")
                        .HasColumnType("int");

                    b.Property<short>("EmployeeRole")
                        .HasColumnType("smallint");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("EmployeeLevelId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("RequestsManagementSystem.Core.Entities.EmployeeLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CasualLeavePerYear")
                        .HasColumnType("int");

                    b.Property<string>("LevelDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("RegularLeaveperYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EmployeeLevel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CasualLeavePerYear = 6,
                            LevelDescription = "الفئة أ",
                            LevelName = "A",
                            OrderId = 1,
                            RegularLeaveperYear = 15
                        },
                        new
                        {
                            Id = 2,
                            CasualLeavePerYear = 6,
                            LevelDescription = "الفئة ب",
                            LevelName = "B",
                            OrderId = 2,
                            RegularLeaveperYear = 24
                        });
                });

            modelBuilder.Entity("RequestsManagementSystem.Core.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Itinerary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RespondDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RespondMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("SeenStatus")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<int>("SubstituteEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SubstituteEmployeeId");

                    b.HasIndex("TypeId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("RequestsManagementSystem.Core.Entities.TransactionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sign")
                        .HasColumnType("int");

                    b.Property<double>("Unit")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TransactionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "إجازة عارضه",
                            Name = "CasualLeave",
                            ParentType = "",
                            Sign = -1,
                            Unit = 1.0
                        },
                        new
                        {
                            Id = 2,
                            Description = "إجازة اعتيادية",
                            Name = "RegularLeave",
                            ParentType = "",
                            Sign = -1,
                            Unit = 1.0
                        },
                        new
                        {
                            Id = 3,
                            Description = "نصف يوم",
                            Name = "HalfDay",
                            ParentType = "RegularLeave",
                            Sign = -1,
                            Unit = 0.5
                        },
                        new
                        {
                            Id = 4,
                            Description = "ربع يوم",
                            Name = "QuarterDay",
                            ParentType = "RegularLeave",
                            Sign = -1,
                            Unit = 0.25
                        },
                        new
                        {
                            Id = 5,
                            Description = "رصيد اعتيادي إضافي",
                            Name = "AdditionalRegularLeave",
                            ParentType = "RegularLeave",
                            Sign = 1,
                            Unit = 1.0
                        },
                        new
                        {
                            Id = 6,
                            Description = "رصيد عارضه إضافي",
                            Name = "AdditionalCasualLeave",
                            ParentType = "CasualLeave",
                            Sign = 1,
                            Unit = 1.0
                        },
                        new
                        {
                            Id = 7,
                            Description = "غياب بأذن",
                            Name = "ExcusedAbsent",
                            ParentType = "",
                            Sign = -1,
                            Unit = 1.0
                        },
                        new
                        {
                            Id = 8,
                            Description = "غياب بدون بأذن",
                            Name = "UnexcusedAbsent",
                            ParentType = "",
                            Sign = -1,
                            Unit = 1.0
                        },
                        new
                        {
                            Id = 9,
                            Description = "يوم كامل",
                            Name = "FullDay",
                            ParentType = "",
                            Sign = 0,
                            Unit = 1.0
                        },
                        new
                        {
                            Id = 10,
                            Description = "يوم جزئي",
                            Name = "PartialDay",
                            ParentType = "",
                            Sign = 0,
                            Unit = 0.5
                        });
                });

            modelBuilder.Entity("RequestsManagementSystem.Core.Entities.Employee", b =>
                {
                    b.HasOne("RequestsManagementSystem.Core.Entities.EmployeeLevel", "EmployeeLevel")
                        .WithMany()
                        .HasForeignKey("EmployeeLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RequestsManagementSystem.Core.Entities.Employee", "Manager")
                        .WithMany("ManagerStaff")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EmployeeLevel");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("RequestsManagementSystem.Core.Entities.Transaction", b =>
                {
                    b.HasOne("RequestsManagementSystem.Core.Entities.Employee", "Employee")
                        .WithMany("Transactions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RequestsManagementSystem.Core.Entities.Employee", "SubstituteEmployee")
                        .WithMany()
                        .HasForeignKey("SubstituteEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RequestsManagementSystem.Core.Entities.TransactionType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("SubstituteEmployee");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("RequestsManagementSystem.Core.Entities.Employee", b =>
                {
                    b.Navigation("ManagerStaff");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
